-- ============================================================================
-- EnergiaSaaS — schema completo do backend (Supabase / Postgres)
-- Extraído do projeto pboizjwwxcnajeuteivp.
-- Contém: extensões, tabelas, RLS, funções (RPC) e grants.
-- Aplique com: supabase db push  (ou cole no SQL Editor do Supabase)
-- ============================================================================

-- ── Extensões ────────────────────────────────────────────────────────────
create extension if not exists pgcrypto  with schema extensions;
create extension if not exists "uuid-ossp" with schema extensions;

-- ============================================================================
-- TABELAS
-- ============================================================================

-- Usuários da plataforma (login por e-mail/senha, sem Supabase Auth)
create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nome text,
  email text not null unique,
  ativo boolean not null default true,
  created_at timestamptz,
  role text not null default 'membro' check (role = any (array['admin','membro'])),
  criado_por text,
  ultimo_acesso timestamptz,
  senha_hash text
);

-- Estado do app por usuário (contratos, contrapartes, MtM, condições de pagamento, layout do dashboard)
create table if not exists public.app_estado (
  id bigint generated by default as identity primary key,
  email text not null,
  chave text not null,
  valor jsonb not null default '{}'::jsonb,
  atualizado_em timestamptz not null default now(),
  unique (email, chave)
);

-- ── Dados de mercado (ONS/ANEEL/BBCE) — série IPDO e correlatos ────────────
create table if not exists public.ipdo_ear (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  subsistema text not null,
  ear_pct numeric,
  ear_mwmes numeric,
  ear_maxima_mwmes numeric,
  ear_minima_mwmes numeric,
  fonte text default 'ONS',
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_ena (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  subsistema text not null,
  ena_mwmes numeric,
  ena_pct_mlt numeric,
  ena_mlt_referencia numeric,
  tipo text default 'verificada',
  fonte text default 'ONS',
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_cmo_pld (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  semana_operativa text,
  subsistema text not null,
  patamar text default 'medio',
  cmo numeric,
  pld numeric,
  pld_piso numeric,
  pld_teto numeric,
  fonte text default 'ONS/CCEE',
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_carga (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  subsistema text not null,
  carga_verificada_mwmed numeric,
  carga_prevista_mwmed numeric,
  desvio_pct numeric,
  fonte text default 'ONS',
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_geracao (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  subsistema text default 'SIN',
  fonte_geracao text not null,
  geracao_mwmed numeric,
  participacao_pct numeric,
  despacho_fora_merit boolean default false,
  fonte text default 'ONS',
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_intercambio (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  de_subsistema text not null,
  para_subsistema text not null,
  fluxo_mwmed numeric,
  limite_mwmed numeric,
  utilizacao_pct numeric,
  restricao_ativa boolean default false,
  fonte text default 'ONS',
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_curtailment (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  subsistema text not null,
  fonte_geracao text not null,
  corte_mwmed numeric,
  motivo text,
  fonte text default 'ONS',
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_resumo_diario (
  id bigint generated by default as identity primary key,
  data_operacao date not null unique,
  data_arquivo date,
  fonte_dados text,
  resumo_operativo text,
  briefing_html text,
  ear_sin_pct numeric,
  pld_se_medio numeric,
  carga_sin_mwmed numeric,
  itens_selecionados integer,
  enviado_email boolean default false,
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_noticias (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  titulo text not null,
  fonte text,
  url text,
  resumo text,
  impacto_trading text,
  severidade text default 'info' check (severidade = any (array['info','alerta','critico'])),
  tags text[],
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_alertas (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  tipo_alerta text not null,
  subsistema text,
  valor_atual numeric,
  limiar numeric,
  mensagem text,
  ativo boolean default true,
  resolvido_em timestamptz,
  criado_em timestamptz default now()
);

create table if not exists public.ipdo_analise_trader (
  id bigint generated by default as identity primary key,
  data_operacao date not null unique,
  cenario_atual text,
  drivers_cp text,
  riscos_mp text,
  rec_compradores text,
  rec_geradores text,
  rec_traders text,
  modelo_ia text default 'claude-sonnet',
  criado_em timestamptz default now()
);

create table if not exists public.pld_forward (
  id bigint generated by default as identity primary key,
  data_referencia date not null,
  data_entrega date not null,
  subsistema text not null default 'SE/CO',
  pld_forward numeric,
  produto text default 'flat' check (produto = any (array['flat','peak','offpeak'])),
  fonte text default 'BBCE',
  criado_em timestamptz default now()
);

create table if not exists public.aneel_bandeiras (
  id bigint generated by default as identity primary key,
  ano_mes text not null unique,
  bandeira text not null check (bandeira = any (array['verde','amarela','vermelha1','vermelha2','escassez'])),
  adicional_rs_kwh numeric,
  vigencia_inicio date,
  vigencia_fim date,
  resolucao_aneel text,
  fonte text default 'ANEEL',
  criado_em timestamptz default now()
);

create table if not exists public.ons_restricoes (
  id bigint generated by default as identity primary key,
  data_operacao date not null,
  codigo_restricao text,
  descricao text not null,
  tipo text check (tipo = any (array['transmissao','geracao','carga','intercambio'])),
  subsistema text,
  impacto_mw numeric,
  inicio_restricao timestamptz,
  fim_restricao timestamptz,
  ativa boolean default true,
  fonte text default 'ONS',
  criado_em timestamptz default now()
);

create table if not exists public.ons_pmo (
  id bigint generated by default as identity primary key,
  semana text not null unique,
  data_inicio date not null,
  data_fim date not null,
  cmo_se_co numeric,
  cmo_sul numeric,
  cmo_ne numeric,
  cmo_norte numeric,
  ear_inicial_sin_pct numeric,
  ear_final_sin_pct numeric,
  risco_deficit_pct numeric,
  despacho_termico_mwmed numeric,
  observacoes text,
  fonte text default 'ONS/PMO',
  criado_em timestamptz default now()
);

-- ── Carteira ACL (contratos comerciais simplificados) ──────────────────────
create table if not exists public.acl_contratos (
  id bigint generated by default as identity primary key,
  codigo_contrato text unique,
  contraparte text,
  tipo text check (tipo = any (array['compra','venda'])),
  montante_mwmed numeric,
  preco_rs_mwh numeric,
  inicio_fornec date,
  fim_fornec date,
  submercado text default 'SE/CO',
  indexador text default 'fixo' check (indexador = any (array['fixo','ipca','igpm','pld'])),
  status text default 'ativo' check (status = any (array['ativo','encerrado','pendente'])),
  observacoes text,
  criado_em timestamptz default now(),
  atualizado_em timestamptz default now()
);

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================
alter table public.usuarios         enable row level security;
alter table public.app_estado       enable row level security;
alter table public.ipdo_ear         enable row level security;
alter table public.ipdo_ena         enable row level security;
alter table public.ipdo_cmo_pld     enable row level security;
alter table public.ipdo_carga       enable row level security;
alter table public.ipdo_geracao     enable row level security;
alter table public.ipdo_intercambio enable row level security;
alter table public.ipdo_curtailment enable row level security;
alter table public.ipdo_resumo_diario enable row level security;
alter table public.ipdo_noticias    enable row level security;
alter table public.ipdo_alertas     enable row level security;
alter table public.ipdo_analise_trader enable row level security;
alter table public.pld_forward      enable row level security;
alter table public.aneel_bandeiras  enable row level security;
alter table public.ons_restricoes   enable row level security;
alter table public.ons_pmo          enable row level security;
alter table public.acl_contratos    enable row level security;

-- ============================================================================
-- FUNÇÕES (RPC) — precisam existir ANTES das policies que as usam (fn_is_admin)
-- ============================================================================

create or replace function public.fn_is_admin()
returns boolean
language sql stable security definer set search_path to 'public'
as $function$
  select exists (
    select 1 from public.usuarios u
    where u.email = lower(auth.jwt() ->> 'email') and u.role = 'admin' and u.ativo
  );
$function$;

-- Login por e-mail/senha (bcrypt via pgcrypto). Retorna vazio se inválido.
create or replace function public.fn_login_senha(p_email text, p_senha text)
returns table(email text, nome text, role text)
language plpgsql security definer set search_path to 'public', 'extensions'
as $function$
declare v record;
begin
  select u.* into v from public.usuarios u where u.email = lower(p_email) and u.ativo limit 1;
  if v is null or v.senha_hash is null then return; end if;
  if crypt(p_senha, v.senha_hash) <> v.senha_hash then return; end if;
  update public.usuarios set ultimo_acesso = now() where id = v.id;
  return query select v.email, v.nome, v.role;
end $function$;

-- Autocadastro (signup) — cria usuário 'membro' com senha própria.
create or replace function public.fn_criar_conta(p_email text, p_senha text, p_nome text default null::text)
returns text
language plpgsql security definer set search_path to 'public', 'extensions'
as $function$
begin
  if p_email is null or p_email !~ '^[^@\s]+@[^@\s]+\.[^@\s]+$' then return 'EMAIL_INVALIDO'; end if;
  if coalesce(length(p_senha),0) < 6 then return 'SENHA_CURTA'; end if;
  if exists (select 1 from public.usuarios where email = lower(p_email)) then return 'DUPLICADO'; end if;
  insert into public.usuarios(nome, email, role, ativo, senha_hash)
    values (coalesce(nullif(p_nome,''), split_part(lower(p_email),'@',1)), lower(p_email), 'membro', true, crypt(p_senha, gen_salt('bf')));
  return 'OK';
exception when unique_violation then return 'DUPLICADO';
end $function$;

-- Verifica se um e-mail está liberado para logar (allowlist / status ativo).
create or replace function public.fn_login_permitido(p_email text)
returns table(permitido boolean, role text, nome text)
language sql stable security definer set search_path to 'public'
as $function$
  select true, u.role, u.nome
  from public.usuarios u
  where u.email = lower(p_email) and u.ativo
  limit 1;
$function$;

create or replace function public.fn_registrar_acesso()
returns void
language plpgsql security definer set search_path to 'public'
as $function$
begin
  update public.usuarios
    set ultimo_acesso = now()
    where email = lower(auth.jwt() ->> 'email');
end $function$;

-- ── Administração de usuários (chamadas pela aba Configurações, exigem admin) ──
create or replace function public.fn_acesso_listar(p_admin text)
returns setof usuarios
language sql security definer set search_path to 'public'
as $function$
  select u.* from public.usuarios u
  where exists (select 1 from public.usuarios a
                where a.email = lower(p_admin) and a.role = 'admin' and a.ativo)
  order by u.id;
$function$;

-- Overload 1: cria usuário já com senha definida pelo admin.
create or replace function public.fn_acesso_add(p_admin text, p_nome text, p_email text, p_senha text, p_role text)
returns text
language plpgsql security definer set search_path to 'public', 'extensions'
as $function$
begin
  if not exists (select 1 from public.usuarios a where a.email = lower(p_admin) and a.role='admin' and a.ativo)
    then return 'NAO_AUTORIZADO'; end if;
  if coalesce(length(p_senha),0) < 6 then return 'SENHA_CURTA'; end if;
  if coalesce(p_role,'membro') not in ('admin','membro') then p_role := 'membro'; end if;
  insert into public.usuarios(nome, email, role, ativo, criado_por, senha_hash)
    values (p_nome, lower(p_email), coalesce(p_role,'membro'), true, lower(p_admin), crypt(p_senha, gen_salt('bf')));
  return 'OK';
exception when unique_violation then return 'DUPLICADO';
end $function$;

-- Overload 2: cria usuário sem senha (define depois via fn_definir_senha).
create or replace function public.fn_acesso_add(p_admin text, p_nome text, p_email text, p_role text)
returns text
language plpgsql security definer set search_path to 'public'
as $function$
begin
  if not exists (select 1 from public.usuarios a where a.email = lower(p_admin) and a.role='admin' and a.ativo)
    then return 'NAO_AUTORIZADO'; end if;
  if coalesce(p_role,'membro') not in ('admin','membro') then p_role := 'membro'; end if;
  insert into public.usuarios(nome, email, role, ativo, criado_por)
    values (p_nome, lower(p_email), coalesce(p_role,'membro'), true, lower(p_admin));
  return 'OK';
exception when unique_violation then return 'DUPLICADO';
end $function$;

create or replace function public.fn_acesso_del(p_admin text, p_email text)
returns text
language plpgsql security definer set search_path to 'public'
as $function$
begin
  if not exists (select 1 from public.usuarios a where a.email = lower(p_admin) and a.role='admin' and a.ativo)
    then return 'NAO_AUTORIZADO'; end if;
  if lower(p_email) = lower(p_admin) then return 'PROPRIO'; end if;
  delete from public.usuarios where email = lower(p_email);
  return 'OK';
end $function$;

create or replace function public.fn_acesso_set_ativo(p_admin text, p_email text, p_ativo boolean)
returns text
language plpgsql security definer set search_path to 'public'
as $function$
begin
  if not exists (select 1 from public.usuarios a where a.email = lower(p_admin) and a.role='admin' and a.ativo)
    then return 'NAO_AUTORIZADO'; end if;
  update public.usuarios set ativo = p_ativo where email = lower(p_email);
  return 'OK';
end $function$;

create or replace function public.fn_definir_senha(p_admin text, p_email text, p_senha text)
returns text
language plpgsql security definer set search_path to 'public', 'extensions'
as $function$
begin
  if not exists (select 1 from public.usuarios a where a.email = lower(p_admin) and a.role='admin' and a.ativo)
    then return 'NAO_AUTORIZADO'; end if;
  if coalesce(length(p_senha),0) < 6 then return 'SENHA_CURTA'; end if;
  update public.usuarios set senha_hash = crypt(p_senha, gen_salt('bf')) where email = lower(p_email);
  return 'OK';
end $function$;

-- ── Persistência do estado do app na nuvem (por usuário) ───────────────────
create or replace function public.fn_estado_salvar(p_email text, p_chave text, p_valor jsonb)
returns void
language plpgsql security definer set search_path to 'public'
as $function$
begin
  if p_email is null or length(trim(p_email)) = 0 then raise exception 'email obrigatorio'; end if;
  insert into public.app_estado(email, chave, valor, atualizado_em)
  values (lower(trim(p_email)), p_chave, coalesce(p_valor,'{}'::jsonb), now())
  on conflict (email, chave) do update set valor = excluded.valor, atualizado_em = now();
end; $function$;

create or replace function public.fn_estado_carregar(p_email text)
returns table(chave text, valor jsonb, atualizado_em timestamptz)
language sql security definer set search_path to 'public'
as $function$
  select chave, valor, atualizado_em from public.app_estado where email = lower(trim(p_email));
$function$;

-- ============================================================================
-- GRANTS de execução (RPCs precisam ser chamáveis pelo cliente anon/publishable)
-- ============================================================================
grant execute on function public.fn_is_admin() to anon, authenticated;
grant execute on function public.fn_login_senha(text, text) to anon, authenticated;
grant execute on function public.fn_criar_conta(text, text, text) to anon, authenticated;
grant execute on function public.fn_login_permitido(text) to anon, authenticated;
grant execute on function public.fn_registrar_acesso() to anon, authenticated;
grant execute on function public.fn_acesso_listar(text) to anon, authenticated;
grant execute on function public.fn_acesso_add(text, text, text, text, text) to anon, authenticated;
grant execute on function public.fn_acesso_add(text, text, text, text) to anon, authenticated;
grant execute on function public.fn_acesso_del(text, text) to anon, authenticated;
grant execute on function public.fn_acesso_set_ativo(text, text, boolean) to anon, authenticated;
grant execute on function public.fn_definir_senha(text, text, text) to anon, authenticated;
grant execute on function public.fn_estado_salvar(text, text, jsonb) to anon, authenticated;
grant execute on function public.fn_estado_carregar(text) to anon, authenticated;

-- ============================================================================
-- POLICIES
-- ============================================================================

-- usuarios: cada usuário vê/edita a si mesmo; admin vê e gerencia todos.
create policy usuarios_select on public.usuarios for select to authenticated
  using (fn_is_admin() or email = lower(auth.jwt() ->> 'email'));
create policy usuarios_insert on public.usuarios for insert to authenticated
  with check (fn_is_admin());
create policy usuarios_update on public.usuarios for update to authenticated
  using (fn_is_admin()) with check (fn_is_admin());
create policy usuarios_delete on public.usuarios for delete to authenticated
  using (fn_is_admin() and email <> lower(auth.jwt() ->> 'email'));

-- app_estado: sem policy de tabela — todo acesso passa pelas RPCs
-- fn_estado_salvar / fn_estado_carregar (SECURITY DEFINER).

-- Dados de mercado (ONS/ANEEL/BBCE): leitura livre para autenticados,
-- escrita restrita a admin. Padrão idêntico em todas as tabelas abaixo.
do $$
declare t text;
begin
  foreach t in array array[
    'ipdo_ear','ipdo_ena','ipdo_cmo_pld','ipdo_carga','ipdo_geracao','ipdo_intercambio',
    'ipdo_curtailment','ipdo_resumo_diario','ipdo_noticias','ipdo_alertas','ipdo_analise_trader',
    'pld_forward','aneel_bandeiras','ons_restricoes','ons_pmo','acl_contratos'
  ] loop
    execute format('create policy %I_auth_select on public.%I for select to authenticated using (true);', t, t);
    execute format('create policy %I_admin_write on public.%I for all to authenticated using (fn_is_admin()) with check (fn_is_admin());', t, t);
  end loop;
end $$;
